Updates to html templates
GroupProjectSysc4806Team5/4806GroupProject pull request #68
Opened 2021-03-31 14:27 UTC by Hussainalbaidhani

- Autowired the Repositories in the controller

- Updated all the html templates:
	- Aligned all elements to the middle of the screen
	- Added links wherever necessary for navigation

2021-03-31 15:16 UTC, jolartabungar commented on src/main/resources/templates/add_book.html
> +	<style type="text/css">
It would be better to abstract these stylings to their own style sheet and then reference in a link tag like what I did with bootstrap. That way if you want to modify it, it's all in one place, since you're using pretty much the same styles on each page. Just make sure the new style sheet is referenced after bootstrap

2021-03-31 15:17 UTC, jolartabungar requested changes
It would be better to use a stylesheet to put all your new styles in and reference them on each page using a link tag. See my comment for more details.

2021-03-31 15:22 UTC, ryantordesillas commented
Ran your changes on my machine, looks good! Just address Jolar's changes and you're good to go!

2021-04-03 00:51 UTC, jolartabungar approved these changes
Looks good

2021-04-03 00:52 UTC, ryantordesillas approved these changes

2021-04-03 01:45 UTC, merged